language: go

go:
  - 1.3
  - 1.4
  - tip

before_install:
  # install linting tools
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/fzipp/gocyclo
  # install code coverage tools
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go get -t
  - go build

script:
  # make sure code is properly formatted and simplified
  - find . -path ./Godeps -prune -o -name '*.go' -exec gofmt -l -s {} +
  # check for possible uh ohs
  - go vet ./...
  # run tests checking for race conditions
  - go test ./... -v -race
  # report test coverage
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken=$COVERALLS

after_success:
  # check possible styling errors
  - golint ./...
  # check for potentially complex functions
  - gocyclo -over 15